[browser]
gatherUsageStats = false

[theme]
primaryColor="#df6263"  # Genpact coral
backgroundColor="#ffffff"  # White background
secondaryBackgroundColor="#4aabca"   
textColor="#1e345c"  # Genpact Blue
base = "light"